### ISSUE TITLE
Revamps `deprecated` mappings

### ISSUE THREAD

**Issue by ducthotran2010** [axieinfinity/ronin-dpos-contracts#120]
https://skymavis.atlassian.net/browse/PSC-131?atlOrigin=eyJpIjoiY2FiYjYxMzM3NGJlNDRhM2FjZjk0ZmUzYmU4NDY2OGYiLCJwIjoiaiJ9
I guess we can clear these mappings since the reward amount is stored in decimal number:

https://github.com/axieinfinity/ronin-dpos-contracts/blob/11e59476037ffaf45b7da3d430682b068b69977f/contracts/ronin/validator/storage-fragments/JailingStorage.sol#L9-L10

https://github.com/axieinfinity/ronin-dpos-contracts/blob/11e59476037ffaf45b7da3d430682b068b69977f/contracts/ronin/validator/storage-fragments/JailingStorage.sol#L13-L14

**Comment by nxqbao** [comment]
What does it mean by `the reward amount is stored in decimal number`?

**Comment by ducthotran2010** [comment]
https://github.com/axieinfinity/ronin-dpos-contracts/blob/11e59476037ffaf45b7da3d430682b068b69977f/contracts/ronin/validator/storage-fragments/CommonStorage.sol#L11-L19

**Comment by ducthotran2010** [comment]
**Review the mapping `_miningRewardDeprecatedAtPeriod`**
There is [an unavailability slashing for the block producer that marks the mapping](https://github.com/axieinfinity/ronin-dpos-contracts/blob/d722d7bfab217bd47e64c72946d6b051b7d7b6eb/contracts/ronin/validator/SlashingExecution.sol#L25). When (s)he is slashed tier-1, the next reward in the period should be deprecated which defined at the function to submit block reward:
https://github.com/axieinfinity/ronin-dpos-contracts/blob/d722d7bfab217bd47e64c72946d6b051b7d7b6eb/contracts/ronin/validator/CoinbaseExecution.sol#L57-L59
^ It's necessary to keep a mapping to mark whether the mining reward is deprecated or not.

**Review the mapping `_bridgeRewardDeprecatedAtPeriod`**
In theory, we can check whether the bridge operating reward is larger than 0 instead. But I guess we are fine to leave it for consistency with the above mapping.

We decided to not change anything related to these mappings, their existence is necessary
