### ISSUE TITLE
Confusing variable name in Staking contract

### ISSUE THREAD

**Issue by ducthotran2010** [axieinfinity/ronin-dpos-contracts#69]
### Multiple meanings of staking amount
- This staking amount implies the delegating amount:
https://github.com/axieinfinity/ronin-dpos-contracts/blob/22060de1ba5187670405e2cfedf8c5daf4774a67/contracts/interfaces/staking/IRewardPool.sol#L45-L56 
- This staking amount implies the self-staking amount of a validator/pool:
https://github.com/axieinfinity/ronin-dpos-contracts/blob/22060de1ba5187670405e2cfedf8c5daf4774a67/contracts/interfaces/staking/IBaseStaking.sol#L16-L17

### Recommend
**Delegate -> Stake; Stake -> Self-Staking**
- stake/unstake -> selfStake/selfUnstake
- This variable can be renamed to `selfStakingAmount`:
https://github.com/axieinfinity/ronin-dpos-contracts/blob/22060de1ba5187670405e2cfedf8c5daf4774a67/contracts/interfaces/staking/IBaseStaking.sol#L16-L17

**Comment by nxqbao** [comment]
It's okay to leave it as it be.
